DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(191) UNIQUE NOT NULL,
  name VARCHAR(191) NOT NULL,
  leader_name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  phone VARCHAR(191) NOT NULL,
  region VARCHAR(191) NOT NULL,
  city VARCHAR(191) NOT NULL,
  national_id VARCHAR(191) NOT NULL,
  job VARCHAR(191) NOT NULL,
  organization VARCHAR(191) NOT NULL,
  status VARCHAR(191) DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
